name: iOS CI

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    name: Build & Test
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          xcodebuild \
            -project Moha/Moha.xcodeproj \
            -scheme Moha \
            -sdk iphonesimulator \
            -destination 'generic/platform=iOS Simulator' \
            CODE_SIGNING_ALLOWED=NO \
            clean build
